name: Develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build dev

  docker:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    needs: build
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets: inherit
